
title: Amner.me
email: jdamner@me.com
telephone: "07515352631"
description: >-
  A personal site full of personal thoughts from a mortgage adviser turned web developer.
baseurl: ""
url: "https://amner.me"

blog:
  title: "My Projects"
  preamble: "Just a few personal projects, some writing, and other bits that might be interesting"

footer:
  #copyright is prefixed with &copy; and postfixed with current year
  copyright: "James Amner"
  image:
    src: "/assets/footer.jpg"
    caption: "Balboa and I hard at work"

# Build settings
# theme: amner-me
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
