
title: James Amner
email: jdamner@me.com
telephone: "07515352631"
description: >-
  A personal site full of personal thoughts from a web developer.
baseurl: ""
url: "https://amner.me"

blog:
  title: "My Projects and Writing"
  preamble: "A few things I've done, a few things I think about and a few things that have nowhere else to be."
  read_more: "Something else?"

contact:
  title: "Say Hello"
  preamble: "Looking for someone just like me?"
footer:
  #copyright is prefixed with &copy; and postfixed with current year
  copyright: "James Amner"

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - node_modules/
  - build.js
  - firebase.json
  - package*