version: '3'
services: 
  app:
    image: node:20
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - '3000:3000'
    command: npm run dev
  playwright:
    image: mcr.microsoft.com/playwright
    volumes:
      - .:/app
    working_dir: /app
    command: npm run test