version: '3'
services: 
  app:
    image: node:lts
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - '3000:3000'
    command: npm start
  playwright:
    image: mcr.microsoft.com/playwright:focal
    volumes:
      - .:/app
    working_dir: /app
    command: npm run test:vr