name: CI

on:
  pull_request:
    branches:
      - staging
      - main

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  run_jest:
    name: Run Jest Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Jest tests
        run: npm run test:ci
      - uses: actions/upload-artifact@v2 
        if: success() || failure() 
        with:
          name: jest-results
          path: jest-results.xml
  run_vr:
    name: Run VR Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps
      - name: Run VR Tests
        run: npm run test:vr
      - uses: actions/upload-artifact@v2 
        if: success() || failure() 
        with:
          name: vr-results
          path: vr-results.xml
  update_snapshots:
    name: Update Test Snapshots
    needs: [run_jest, run_vr]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps
      - name: Update snapshots
        run: npm run update-snapshots
      - name: Create PR
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global push.autoSetupRemote true
          git checkout -b vr-image-update/${{ github.sha }}
          git add .
          git commit -m "Update VR images"
          git push origin
          gh pr create --title "Update VR images" --body "Update VR images" --base ${{ github.event.pull_request.head.ref }} --head vr-image-update/${{ github.sha }} --label "VR test update"
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy_for_review:
    name: Deploy for review
    runs-on: ubuntu-latest
    needs: [run_jest, run_vr]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build Next app
        run: npm run build
      - name: 'Deploy'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entrypoint: ./
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AMNER_ME }}'
          expires: 30d
          projectId: amner-me

