name: CI

on:
  pull_request:
    branches:
      - staging
      - main

permissions:
  contents: write
  pull-requests: write
  checks: write
  issues: write

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        project: [chromium, chromium-mobile, firefox, webkit, webkit-mobile, chromium-dark, chromium-mobile-dark, firefox-dark, webkit-dark, webkit-mobile-dark]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci && npx playwright install --with-deps
      - name: Run VR Tests
        run: npx playwright test --project=${{ matrix.project }}
      - name: Publish Test Results
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'results.xml'
  update_snapshots:
    name: Update Test Snapshots
    needs: [tests]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci && npx playwright install --with-deps
      - name: Update snapshots
        run: npx playwright test --update-snapshots
      - name: Create PR
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global push.autoSetupRemote true
          git checkout -b vr-image-update/${{ github.sha }}
          git add .
          git commit -m "Update VR images"
          git push origin
          gh pr create --title "Update VR images" --body "Update VR images" --base ${{ github.event.pull_request.head.ref }} --head vr-image-update/${{ github.sha }} --label "VR test update"
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy_for_review:
    name: Deploy for review
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build Next app
        run: npm run build
      - name: 'Deploy'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entrypoint: ./
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AMNER_ME }}'
          expires: 30d
          projectId: amner-me
