name: CI

on:
  pull_request:
    branches:
      - staging
      - main

permissions:
  contents: write
  pull-requests: write
  checks: write
  issues: write

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        playwright: [chromium, chromium-mobile, webkit-mobile, chromium-dark, chromium-mobile-dark, webkit-mobile-dark]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci && npx playwright install --with-deps
      - name: Run VR Tests
        run: npx playwright test --project=${{ matrix.playwright }}
      - name: Publish Test Results
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'results.xml'
          fail_on_failure: false
          require_tests: false
          job_name: ${{ matrix.playwright }} Results
  update_snapshots:
    name: Update Test Snapshots
    needs: [tests]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        playwright: [chromium, chromium-mobile, webkit-mobile, chromium-dark, chromium-mobile-dark, webkit-mobile-dark]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci && npx playwright install --with-deps
      - name: Update snapshots
        run: npx playwright test --project=${{ matrix.playwright }} --update-snapshots
      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Automated request to update snapshots for ${{ matrix.playwright }}'
          title: 'Updated snapshots for ${{ matrix.playwright }}'
          body: 'Automated request to update snapshots for ${{ matrix.playwright }}'
          branch: 'update-snapshots'
          branch-suffix: short-commit-hash
          base: ${{ github.event.pull_request.head.ref }}
          labels: 'VR Test Update'
          delete-branch: true
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy_for_review:
    name: Deploy for review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build Next app
        run: npm run build
      - name: 'Deploy'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entrypoint: ./
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AMNER_ME }}'
          expires: 30d
          projectId: amner-me
