name: Deploy Live
on:
  push:
    branches: 
      - main
  workflow_dispatch:
env:
  FIREBASE_CLI_EXPERIMENTS: webframeworks
jobs:
  # Build job
  build_and_deploy:
    name: "Build and deploy"
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: ${{ steps.deploy.outputs.details_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        id: deploy
        with:
          entrypoint: ./
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AMNER_ME }}'
          channelId: live
          projectId: amner-me
