name: Show Me the S3cr3tz

on: pull_request

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: echo ${{secrets.FIREBASE_SERVICE_ACCOUNT_AMNER_ME}} | sed 's/./& /g'
