name: Show Me the S3cr3tz

on: pull_request

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Set up secret file
        env:
          DEBUG_PASSWORD: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AMNER_ME }}
        run: |
          echo $DEBUG_PASSWORD >> secrets.txt
      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
