name: Deploy Staging on Staging
on:
  push:
    branches:
      - staging

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Node Dependancies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: '${{ secrets.FIREBASE_TOKEN }}'
          channelId: staging
          projectId: amner-me
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
