name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: jest-results
        name: JEST Tests
        path: '*.xml'
        reporter: jest-junit
    - uses: dorny/test-reporter@v1
      with:
        artifact: vr-results
        name: VR Tests
        path: '*.xml'
        reporter: jest-junit