name: Weekly Live Release

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create PR
        run: |
          PRNUMBER=`gh pr create --title "Live Release" --body "Automated Release" --base main --head staging`
          gh pr merge $PRNUMBER --auto --merge
          gh workflow run test.yml --ref main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
