name: Weekly Live Release

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create PR
        run: |
          PRNUMBER=gh pr create --title "Live Release" --base main --head staging
          gh pr review $PRNUMBER --approve
          gh pr merge $PRNUMBER --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}